rules:
- condition: fragile == True
  department: Fragile
  name: Fragile Item
  priority: 0
- condition: value > 1000
  department: Insurance
  name: High Value Insurance
  priority: 1
- condition: weight <= 1
  department: Mail
  name: Lightweight Mail
  priority: 2
- condition: weight > 1 and weight <= 10
  department: Regular
  name: Regular Parcel
  priority: 3
- condition: weight > 10
  department: Heavy
  name: Heavyweight Parcel
  priority: 4
